### ISSUE TITLE
App not available

### ISSUE THREAD

**Issue by josdyr** [hadig/Focus-for-Youtube#1]
It seems like this app or extension is not available on the App Store anymore. At least it says so from clicking the link provided in the Readme. I really liked this extension. Let me know what is happening. I might be able to help you. 👍

**Comment by hadig** [comment]
Hi,
my Apple Developer Membership expired and for now I am not going to pay for renewing it.
Will try to get the apk up as a download here on github asap

**Comment by hadig** [comment]
Could you please test if the app installs as expected? 
I will look into getting the app notarized and also on brew package manager for a better installation experience. But for now you can find the app under the release section https://github.com/hadig/Focus-for-Youtube/releases
