### ISSUE TITLE
The application does not show up on safari extensions.

### ISSUE THREAD

**Issue by umkl** [hadig/Focus-for-Youtube#2]
Because I cannot find it in the Safari Extensions Tab I am not capable of enabling it. When I start the app it just loads forever? Am I doing anything wrong? Thanks, Regards.

**Comment by hadig** [comment]
hi. this is strange I'm on macOS 12 beta with Safari 15.1 and this extension still works here.
But instead of the app you can integrate the filter list into Safari with AdGuard. I updated the README with further instructions
