### ISSUE TITLE
Add iPad Safari extension support

### ISSUE THREAD

**Issue by jonk** [hadig/Focus-for-Youtube#5]
With iPadOS 15, Safari on iPad now supports web extensions. Any interest in updating to support this, it might be as simple as rebuilding the project. See below

[https://developer.apple.com/safari/extensions/](https://developer.apple.com/safari/extensions/)

**Comment by hadig** [comment]
Hi, great suggestion! 
It is simple as you said, the issue is distribution on iOS/iPadOS. I will not pay the yearly fee to do that.

As a workaround I updated the README with instructions for iOS/iPadOS usage.
Tell me if it works out for you and feel free to improve the README with a PR!
